// <auto-generated />
using BizzWhizzApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BizzWhizzApi.Migrations
{
    [DbContext(typeof(BizzWhizzApiContext))]
    partial class BizzWhizzApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BizzWhizzApi.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BusinessLocation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BusinessName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BusinessType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("BusinessId");

                    b.ToTable("businesses");
                });
#pragma warning restore 612, 618
        }
    }
}
